[project]
name = "251030-snrna-10xflex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geoparse>=2.0.4",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
]
